# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Thomas Kerbrat Blog
email: kerbrat@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  A developer blog about front-end development, software engineering and more.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://thomaskerbrat.github.io" # the base hostname & protocol for your site
twitter_username: KerbratThomas
github_username:  ThomasKerbrat
repository: ThomasKerbrat/blog

# Build settings
markdown: kramdown
